# Generated by Django 5.1.1 on 2024-09-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('permite_recorrencia', models.BooleanField(default=False)),
                ('quantidade_recorrencia', models.PositiveIntegerField()),
                ('intervalo_recorrencia', models.PositiveIntegerField()),
                ('status_recorrencia', models.CharField(max_length=50)),
                ('agencia', models.PositiveIntegerField()),
                ('conta', models.PositiveIntegerField()),
                ('valor_pagamento', models.IntegerField()),
            ],
        ),
    ]
